version: '3.8'
services:
  
  # Backend Service
  backend:
    build: ./doctor-office-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/appointments
      - PORT=3000
    command: "npm start"
    restart: always

  # Frontend Service
  frontend:
    build: ./doctor-office-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - PORT=3001
      - REACT_APP_API_URL=http://localhost:3000 # Use localhost for browser access
    restart: always

  # MongoDB Service
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always