apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 992382470769.dkr.ecr.us-west-1.amazonaws.com/test-app:backend
        ports:
        - containerPort: 3001
        env:
        - name: REACT_APP_BACKEND_URL
          value: "/api"  # Changed to use relative path
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP  # Changed from LoadBalancer to ClusterIP